"""add_study_records

Revision ID: 1c7d662b19b7
Revises: 2938282d377b
Create Date: 2026-01-30 19:17:18.035955

"""
from alembic import op
import sqlalchemy as sa


revision = '1c7d662b19b7'
down_revision = '2938282d377b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_records_content_id'), 'study_records', ['content_id'], unique=False)
    op.create_index(op.f('ix_study_records_content_type'), 'study_records', ['content_type'], unique=False)
    op.create_index(op.f('ix_study_records_id'), 'study_records', ['id'], unique=False)
    op.create_index(op.f('ix_study_records_user_id'), 'study_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_records_user_id'), table_name='study_records')
    op.drop_index(op.f('ix_study_records_id'), table_name='study_records')
    op.drop_index(op.f('ix_study_records_content_type'), table_name='study_records')
    op.drop_index(op.f('ix_study_records_content_id'), table_name='study_records')
    op.drop_table('study_records')
    # ### end Alembic commands ###
