"""normalize_tags

Revision ID: 26a4e7fc7012
Revises: 6c32b62b6d12
Create Date: 2026-01-30 18:40:42.156563

"""
from alembic import op
import sqlalchemy as sa


revision = '26a4e7fc7012'
down_revision = '6c32b62b6d12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('exercise_tags',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'tag_id')
    )
    op.create_table('passage_tags',
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('passage_id', 'tag_id')
    )
    op.create_table('sentence_tags',
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sentence_id', 'tag_id')
    )
    op.create_table('word_tags',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('word_id', 'tag_id')
    )
    connection = op.get_bind()

    def migrate_tags(
        source_table: str,
        id_column: str,
        tags_column: str,
        link_table: str,
        link_column: str,
    ) -> None:
        rows = connection.execute(
            sa.text(
                f"SELECT {id_column}, {tags_column} "
                f"FROM {source_table} "
                f"WHERE {tags_column} IS NOT NULL AND {tags_column} <> ''"
            )
        ).fetchall()
        for item_id, tags_value in rows:
            tags = [tag.strip().lower() for tag in tags_value.split(",") if tag.strip()]
            for tag_name in tags:
                connection.execute(
                    sa.text("INSERT INTO tags (name) VALUES (:name) ON CONFLICT (name) DO NOTHING"),
                    {"name": tag_name},
                )
                tag_id = connection.execute(
                    sa.text("SELECT id FROM tags WHERE name = :name"),
                    {"name": tag_name},
                ).scalar_one()
                connection.execute(
                    sa.text(
                        f"INSERT INTO {link_table} ({link_column}, tag_id) "
                        f"VALUES (:item_id, :tag_id) ON CONFLICT DO NOTHING"
                    ),
                    {"item_id": item_id, "tag_id": tag_id},
                )

    migrate_tags("words", "id", "tags", "word_tags", "word_id")
    migrate_tags("sentences", "id", "tags", "sentence_tags", "sentence_id")
    migrate_tags("passages", "id", "tags", "passage_tags", "passage_id")
    migrate_tags("exercises", "id", "tags", "exercise_tags", "exercise_id")

    op.drop_column('exercises', 'tags')
    op.drop_column('passages', 'tags')
    op.drop_column('sentences', 'tags')
    op.drop_column('words', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('tags', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('sentences', sa.Column('tags', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('passages', sa.Column('tags', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('tags', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    connection = op.get_bind()
    connection.execute(
        sa.text(
            "UPDATE words SET tags = t.tags "
            "FROM (SELECT wt.word_id, string_agg(tags.name, ',') AS tags "
            "FROM word_tags wt JOIN tags ON tags.id = wt.tag_id "
            "GROUP BY wt.word_id) AS t "
            "WHERE words.id = t.word_id"
        )
    )
    connection.execute(
        sa.text(
            "UPDATE sentences SET tags = t.tags "
            "FROM (SELECT st.sentence_id, string_agg(tags.name, ',') AS tags "
            "FROM sentence_tags st JOIN tags ON tags.id = st.tag_id "
            "GROUP BY st.sentence_id) AS t "
            "WHERE sentences.id = t.sentence_id"
        )
    )
    connection.execute(
        sa.text(
            "UPDATE passages SET tags = t.tags "
            "FROM (SELECT pt.passage_id, string_agg(tags.name, ',') AS tags "
            "FROM passage_tags pt JOIN tags ON tags.id = pt.tag_id "
            "GROUP BY pt.passage_id) AS t "
            "WHERE passages.id = t.passage_id"
        )
    )
    connection.execute(
        sa.text(
            "UPDATE exercises SET tags = t.tags "
            "FROM (SELECT et.exercise_id, string_agg(tags.name, ',') AS tags "
            "FROM exercise_tags et JOIN tags ON tags.id = et.tag_id "
            "GROUP BY et.exercise_id) AS t "
            "WHERE exercises.id = t.exercise_id"
        )
    )
    op.drop_table('word_tags')
    op.drop_table('sentence_tags')
    op.drop_table('passage_tags')
    op.drop_table('exercise_tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
