"""add_users

Revision ID: 2938282d377b
Revises: 8410bd99e233
Create Date: 2026-01-30 19:14:22.704275

"""
from alembic import op
import sqlalchemy as sa


revision = '2938282d377b'
down_revision = '8410bd99e233'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index(op.f('idx_exercise_tags_exercise_id'), table_name='exercise_tags')
    op.drop_index(op.f('idx_exercise_tags_tag_id'), table_name='exercise_tags')
    op.drop_index(op.f('exercises_fts_idx'), table_name='exercises', postgresql_using='gin')
    op.drop_index(op.f('idx_passage_tags_passage_id'), table_name='passage_tags')
    op.drop_index(op.f('idx_passage_tags_tag_id'), table_name='passage_tags')
    op.drop_index(op.f('passages_fts_idx'), table_name='passages', postgresql_using='gin')
    op.drop_index(op.f('idx_sentence_tags_sentence_id'), table_name='sentence_tags')
    op.drop_index(op.f('idx_sentence_tags_tag_id'), table_name='sentence_tags')
    op.drop_index(op.f('sentences_fts_idx'), table_name='sentences', postgresql_using='gin')
    op.drop_index(op.f('idx_word_tags_tag_id'), table_name='word_tags')
    op.drop_index(op.f('idx_word_tags_word_id'), table_name='word_tags')
    op.drop_index(op.f('words_fts_idx'), table_name='words', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('words_fts_idx'), 'words', [sa.literal_column("to_tsvector('simple'::regconfig, (((COALESCE(text, ''::character varying)::text || ' '::text) || COALESCE(meaning, ''::text)) || ' '::text) || COALESCE(example, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_word_tags_word_id'), 'word_tags', ['word_id'], unique=False)
    op.create_index(op.f('idx_word_tags_tag_id'), 'word_tags', ['tag_id'], unique=False)
    op.create_index(op.f('sentences_fts_idx'), 'sentences', [sa.literal_column("to_tsvector('simple'::regconfig, (COALESCE(text, ''::text) || ' '::text) || COALESCE(meaning, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_sentence_tags_tag_id'), 'sentence_tags', ['tag_id'], unique=False)
    op.create_index(op.f('idx_sentence_tags_sentence_id'), 'sentence_tags', ['sentence_id'], unique=False)
    op.create_index(op.f('passages_fts_idx'), 'passages', [sa.literal_column("to_tsvector('simple'::regconfig, (((COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(content, ''::text)) || ' '::text) || COALESCE(summary, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_passage_tags_tag_id'), 'passage_tags', ['tag_id'], unique=False)
    op.create_index(op.f('idx_passage_tags_passage_id'), 'passage_tags', ['passage_id'], unique=False)
    op.create_index(op.f('exercises_fts_idx'), 'exercises', [sa.literal_column("to_tsvector('simple'::regconfig, (((COALESCE(prompt, ''::text) || ' '::text) || COALESCE(answer, ''::text)) || ' '::text) || COALESCE(explanation, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_exercise_tags_tag_id'), 'exercise_tags', ['tag_id'], unique=False)
    op.create_index(op.f('idx_exercise_tags_exercise_id'), 'exercise_tags', ['exercise_id'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
