"""add_plans_and_reminders

Revision ID: 588157feac58
Revises: 1c7d662b19b7
Create Date: 2026-01-30 19:19:47.874138

"""
from alembic import op
import sqlalchemy as sa


revision = '588157feac58'
down_revision = '1c7d662b19b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_reminders_content_id'), 'review_reminders', ['content_id'], unique=False)
    op.create_index(op.f('ix_review_reminders_content_type'), 'review_reminders', ['content_type'], unique=False)
    op.create_index(op.f('ix_review_reminders_id'), 'review_reminders', ['id'], unique=False)
    op.create_index(op.f('ix_review_reminders_next_review_at'), 'review_reminders', ['next_review_at'], unique=False)
    op.create_index(op.f('ix_review_reminders_status'), 'review_reminders', ['status'], unique=False)
    op.create_index(op.f('ix_review_reminders_user_id'), 'review_reminders', ['user_id'], unique=False)
    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('daily_target', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_plans_id'), 'study_plans', ['id'], unique=False)
    op.create_index(op.f('ix_study_plans_user_id'), 'study_plans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_plans_user_id'), table_name='study_plans')
    op.drop_index(op.f('ix_study_plans_id'), table_name='study_plans')
    op.drop_table('study_plans')
    op.drop_index(op.f('ix_review_reminders_user_id'), table_name='review_reminders')
    op.drop_index(op.f('ix_review_reminders_status'), table_name='review_reminders')
    op.drop_index(op.f('ix_review_reminders_next_review_at'), table_name='review_reminders')
    op.drop_index(op.f('ix_review_reminders_id'), table_name='review_reminders')
    op.drop_index(op.f('ix_review_reminders_content_type'), table_name='review_reminders')
    op.drop_index(op.f('ix_review_reminders_content_id'), table_name='review_reminders')
    op.drop_table('review_reminders')
    # ### end Alembic commands ###
