"""add_wrong_items

Revision ID: a2df3151b5a9
Revises: 588157feac58
Create Date: 2026-01-30 19:22:55.944465

"""
from alembic import op
import sqlalchemy as sa


revision = 'a2df3151b5a9'
down_revision = '588157feac58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wrong_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('last_wrong_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wrong_items_content_id'), 'wrong_items', ['content_id'], unique=False)
    op.create_index(op.f('ix_wrong_items_content_type'), 'wrong_items', ['content_type'], unique=False)
    op.create_index(op.f('ix_wrong_items_id'), 'wrong_items', ['id'], unique=False)
    op.create_index(op.f('ix_wrong_items_user_id'), 'wrong_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wrong_items_user_id'), table_name='wrong_items')
    op.drop_index(op.f('ix_wrong_items_id'), table_name='wrong_items')
    op.drop_index(op.f('ix_wrong_items_content_type'), table_name='wrong_items')
    op.drop_index(op.f('ix_wrong_items_content_id'), table_name='wrong_items')
    op.drop_table('wrong_items')
    # ### end Alembic commands ###
