"""add_mock_exams

Revision ID: b38cf1bb667c
Revises: a2df3151b5a9
Create Date: 2026-01-30 19:24:27.881467

"""
from alembic import op
import sqlalchemy as sa


revision = 'b38cf1bb667c'
down_revision = 'a2df3151b5a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('exercise_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_exams_id'), 'mock_exams', ['id'], unique=False)
    op.create_index(op.f('ix_mock_exams_user_id'), 'mock_exams', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mock_exams_user_id'), table_name='mock_exams')
    op.drop_index(op.f('ix_mock_exams_id'), table_name='mock_exams')
    op.drop_table('mock_exams')
    # ### end Alembic commands ###
