"""add_exam_configs

Revision ID: e32a1887daec
Revises: 8b4baeac9ad4
Create Date: 2026-01-30 19:29:02.414474

"""
from alembic import op
import sqlalchemy as sa


revision = 'e32a1887daec'
down_revision = '8b4baeac9ad4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=True),
    sa.Column('distribution', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_configs_id'), 'exam_configs', ['id'], unique=False)
    op.create_index(op.f('ix_exam_configs_name'), 'exam_configs', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_configs_name'), table_name='exam_configs')
    op.drop_index(op.f('ix_exam_configs_id'), table_name='exam_configs')
    op.drop_table('exam_configs')
    # ### end Alembic commands ###
